name: ddd-viewer build
run-name:  Full build has been triggered by (${{ github.actor }})
on:
  push:
    branches:
      - master
    #tags:
    #  - 'v*'
jobs:
  build:
    name: Build job on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        node: [ '18.0', '20.0']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      # - name: Remove lock files under windows systems
      #  run: |
      #    if exist "./package-lock.json" del "./package-lock.json"
      #    if exist "./yarn-lock.json" del "./yarn-lock.json"

      - name: Remove lock files under non-windows systems
        run: |
          rm -rf ./package-lock.json
          rm -rf ./yarn-lock.json
        if: matrix.os != 'windows-latest'

      - name: Install dependencies
        run: |
          yarn

      - name: Lint
        run: yarn lint

      # - name: Audit
      #  run: yarn audit

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
        run: yarn build

      #- name: Deploy GitHub pages
      #  run: |
      #    mkdir -p ./examples/simple/lib/
      #    cp dist/ddd-viewer.umd.production.min.js examples/simple/lib/ddd-viewer.umd.production.min.js
      #    node ci/publish-gh-pages.js
      #  if: matrix.os == 'ubuntu-latest' && matrix.node == '20.0'
